# Options
options:
  path:
    output: results.txt

# Transaction Collections
collections:
  income:
    name: Income
    classifiers:
      tags:
        - Income : Other Income
      accounts:
        - Job 1
        - Job 2
  expenses:
    name: Expenses
    threshold:
      value: 20
      percentage: 10
  savings:
    name: Savings
    classifiers:
      accounts: 
        - Investment Account 1 : Investments
        - Investment Account 2 : Investments
        - Savings Account 1 : Savings

# Ignored transactions
ignore:
  accounts:
    - Closed Account
  tags:
    - Ignored Transaction
